### ISSUE TITLE
Explore stable diffusion support in Torch-TRT

### ISSUE THREAD

**Issue by Christina-Young-NVIDIA** [pytorch/TensorRT#1545]
```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/TensorRT/issues/2144
- [ ] https://github.com/pytorch/TensorRT/issues/2183
- [ ] https://github.com/pytorch/TensorRT/pull/2175
- [ ] https://github.com/pytorch/TensorRT/pull/2182
- [ ] https://github.com/pytorch/TensorRT/pull/2161
- [ ] https://github.com/pytorch/TensorRT/pull/2173
- [ ] https://github.com/pytorch/TensorRT/issues/2124
```

**Comment by gs-olive** [comment]
## Full Set of Current Missing Operators for Stable Diffusion
```
##### Other Sub-Architectures
- torch.ops.aten.bmm.default
- torch.ops.aten.linalg_vector_norm.default
- torch.ops.aten.clamp_min.default
- torch.ops.aten.repeat.default
- torch.ops.aten.full.default
- torch.ops.aten.randn.generator

##### UNet
- torch.ops.aten.arange.start_step + Operator Count: 7
- torch.ops.aten.exp.default + Operator Count: 1
- torch.ops.aten._to_copy.default + Operator Count: 7
- torch.ops.aten.sin.default + Operator Count: 1
- torch.ops.aten.cos.default + Operator Count: 1
- torch.ops.aten.native_group_norm.default + Operator Count: 61
- _operator.getitem + Operator Count: 173
- torch.ops.aten.native_layer_norm.default + Operator Count: 48
- torch.ops.aten._scaled_dot_product_efficient_attention.default + Operator Count: 32
- torch.ops.aten.split.Tensor + Operator Count: 16
- torch.ops.aten.clone.default + Operator Count: 16
- torch.ops.aten._unsafe_index.Tensor + Operator Count: 3
```
