### ISSUE TITLE
📖 [Story] TorchScript / Dynamo Feature Parity 

### ISSUE THREAD

**Issue by narendasan** [pytorch/TensorRT#1992]
## TL;DR

Features such as quantization need to be ported to dynamo from torchscript

## Goal(s)

Make sure as much of the advanced functionality we have added to Torchscript is reflected in dyamo

## Additional context

```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/TensorRT/issues/2123
- [ ] https://github.com/pytorch/TensorRT/issues/2134
- [ ] https://github.com/pytorch/TensorRT/issues/2135
```
