### ISSUE TITLE
📖 [Story] Infrastructure Upgrades

### ISSUE THREAD

**Issue by narendasan** [pytorch/TensorRT#2034]
## TL;DR

There are a number of tasks to upgrade the infrastructure for the project

## Goal(s)

Modernize the infra.

```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/TensorRT/issues/1946
- [ ] https://github.com/pytorch/TensorRT/issues/2035
- [ ] https://github.com/pytorch/TensorRT/issues/2012
- [ ] https://github.com/pytorch/TensorRT/issues/1993
```
