### ISSUE TITLE
📖 [Story] High Priority Operator Support

### ISSUE THREAD

**Issue by narendasan** [pytorch/TensorRT#2230]
## TL;DR

These operations are high priority to have native support

## Goal(s)

Operations that have high impact in key models should be the ones we focus on supporting first past core support of TRT operations.

## Tasks
```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/TensorRT/issues/2231
- [ ] https://github.com/pytorch/TensorRT/issues/2243
- [ ] https://github.com/pytorch/TensorRT/issues/2236
- [ ] https://github.com/pytorch/TensorRT/issues/2244
- [ ] https://github.com/pytorch/TensorRT/issues/2245
- [ ] https://github.com/pytorch/TensorRT/issues/1795
- [x] https://github.com/pytorch/TensorRT/issues/2345
```

## Additional context

See issues like: #2144, #1545

```[tasklist]
### Tasks
```
