### ISSUE TITLE
📖 [Story] Implement support for serde of TRT Graph modules with torch.export serde API

### ISSUE THREAD

**Issue by peri044** [pytorch/TensorRT#2262]
## TL;DR
torch.export has serde API and now supports custom object (in our case `torch.classes.tensorrt.Engine`) serialization. 

## Goal(s)
We should be able to serialize/deserialize the output of torch-trt compilation.

## Tasks
```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/TensorRT/issues/2258
- [ ] https://github.com/pytorch/TensorRT/issues/2259
- [ ] https://github.com/pytorch/TensorRT/issues/2260
- [ ] https://github.com/pytorch/TensorRT/issues/2261
- [ ] https://github.com/pytorch/TensorRT/issues/2270
```
