### ISSUE TITLE
TRT Version Upgrade Investigation

### ISSUE THREAD

**Issue by gs-olive** [pytorch/TensorRT#2532]
```[tasklist]
### Tasks
- [ ] https://github.com/pytorch/TensorRT/issues/2581
- [ ] https://github.com/pytorch/TensorRT/issues/2582
- [ ] https://github.com/pytorch/TensorRT/issues/2583
```

**Comment by gs-olive** [comment]
# Overview of Findings

- Torch-TRT wheels now building successfully in CI within PR #2538 using TRT 9
- Converters failing due to data type changes/mismatches (seem to be minor issues)
- Hardware compatibility test failing due to serialized `.ts` file not being built with version compatibility
