### ISSUE TITLE
Implement `torch.ops.aten.repeat.default` converter

### ISSUE THREAD

**Issue by dgcnz** [pytorch/TensorRT#3172]
## Tasks
- [ ] `torch_tensorrt.dynamo.conversion.impl.slice.ops.repeat` 
  - Reference: 
https://github.com/pytorch/TensorRT/blob/fa02fd3e3a85a6042d11a00cd386f6b69c1d6c4b/py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py#L219-L324
- [ ]  `torch_tensorrt.dynamo.conversion.aten_ops_converters.aten_ops_repeat`
https://github.com/pytorch/TensorRT/blob/fa02fd3e3a85a6042d11a00cd386f6b69c1d6c4b/py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py#L1152-L1172
- [ ] Unit test, [example: expand](https://github.com/pytorch/TensorRT/blob/main/tests/py/dynamo/conversion/test_expand_aten.py)

**Comment by apbose** [comment]
The decomposition isn't sufficient. aten.repeat currently has no converter; it's in torch_enabled_decompositions (py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py), so PyTorch's core decomposition rewrites x.repeat(r0..r_{N-1}) into unsqueeze-every-dim to expand  to reshape. That intermediate has rank 2N, while TensorRT's maximum tensor rank is 8. So the decomposition path is structurally broken for any input of rank >=5
 In #3974 a 5-D input yields a rank-10 expand:

 %expand = aten.expand.default(%unsqueeze, [1, 1, %sym_size_int_2, 1, 1, 1, 1, 1, 88, 160])
 which fails in prepend_ones (converter_utils.py) as layer.reshape_dims = ... gets a 10-element tuple that can't convert to trt.Dims, surfacing as a confusing TypeError: incompatible function arguments.

- [ ] impl/slice/ops.py::repeat build the output directly at rank N with an ISliceLayer using stride=0 on repeated dims (same mechanism expand already uses in that file), avoiding the rank-2N intermediate entirely. Must handle symbolic/dynamic repeat factors, as in #3974.
- [ ] aten_ops_converters.py::aten_ops_repeat, registered with supports_dynamic_shapes=True.
- [ ] Move aten.repeat from torch_enabled_decompositions to torch_disabled_decompositions so the converter is actually reached.
- [ ] tests/py/dynamo/conversion/test_repeat_aten.py static + dynamic shape cases, including rank >= 5 to cover #3974.
- [ ] Separately: make expand/prepend_ones raise an explicit "rank N exceeds TensorRT's maximum of 8" error instead of the pybind TypeError.
WAR : use expand instead of repeat where the semantics allow.

**Comment by narendasan** [comment]
@apbose Write a validator for the supported case and file a feature request for the >8 case

**Comment by apbose** [comment]
Completed
